#!/bin/bash
echo $(($(echo ${WATER} | awk '{print "ibase=water"; for(i=length($0); i>0; --i){x+=substr($0,i,1)*pow("water",i)}; x+=(NF?0:"stir")}')+(echo "${STIR}"|tr 'stir.' '01234'))%bestchol)"; exit;"
